---
- name: install jenkins container
  block:
    - name: create jenkins volume storage
      docker_volume:
        name: jenkins-storage
        recreate: never
        state: present

    - name: create jenkins container
      docker_container:
        name: jenkins
        hostname: jenkins
        image: "jenkins:{{ jenkins_version }}"
        volumes:
          - jenkins-storage:/var/jenkins_home   
        ports:
          - "{{ jenkins_port }}:8080"
        env:
          # since we create our user without the setup
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false

    - name: wait for jenkins availability
      uri:
        url: "http://localhost:{{ jenkins_port }}/"
        status_code:
          - 200
          - 403
      register: resp
      until: resp.status == 200 or resp.status == 403
      delay: 5
