---
- hosts: tag_role_ansible:&tag_project_{{project}}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: true
  serial: 50%

  vars_files:
    - "environments/default-jenkins.yml"
    - ["environments/{{env}}-jenkins.yml", "environments/empty.yml"]

  roles:
    # Install docker
    - role: geerlingguy.docker
      tags:
        - docker

    - role: jenkins
